// src/constants/notificationTypes.js

export const NOTIFICATION_TYPES = {
  ORDER_PLACED: "ORDER_PLACED",
  ORDER_ASSIGNED: "ORDER_ASSIGNED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  CREDIT_REMINDER: "CREDIT_REMINDER",
};

export const NOTIFICATION_TYPE_LIST = Object.values(NOTIFICATION_TYPES);